### ISSUE TITLE
Make python 3 compatible

### ISSUE THREAD

**Issue by jaycle** [alexortizrosado/pyBreezeChMS#6]
Thanks for the library! It looks like there isn't much required to make this python 3 compatible. I haven't had to maintain any packages which span versions so I'm not sure the best approach if you want to maintain backwards compatibility with python 2. For basic functionality (I just started using it) it seems these are all that are needed:
https://github.com/alexortizrosado/pyBreezeChMS/compare/master...jaycle:py3update

**Comment by alexortizrosado** [comment]
Thanks @jaycle! I've merged your change in PR #7
